"""followers

Revision ID: 80e73d11a765
Revises: 5595489f515e
Create Date: 2021-04-28 13:01:52.851515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e73d11a765'
down_revision = '5595489f515e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referencing',
    sa.Column('referenced_id', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reference_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['referenced_id'], ['documents.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referencing')
    # ### end Alembic commands ###
