"""create documents table

Revision ID: 6822ed714d71
Revises: e8c4d42b3e75
Create Date: 2021-01-06 10:36:33.185537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6822ed714d71'
down_revision = 'e8c4d42b3e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('directory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['directories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
